import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import { ThemeProvider } from "./ThemeContext.jsx";
import { ViewportProvider } from "./ViewportContext.jsx";
import { registerSW } from "virtual:pwa-register";

// Registers the service worker generated by vite-plugin-pwa at build time.
// This is what makes the browser offer "Add to Home Screen" / "Install app",
// and lets the app open full-screen without the browser address bar.
registerSW({ immediate: true });

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <ThemeProvider>
      <ViewportProvider>
        <App />
      </ViewportProvider>
    </ThemeProvider>
  </React.StrictMode>
);
